import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: ['tests/{unit,integration}/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: [
        'src/backend/backend-client.ts',
        'src/core/configuration.ts',
        'src/core/chat-attachment.ts',
        'src/core/context-collector.ts',
        'src/core/edit-plan.ts',
        'src/core/extension-state.ts',
        'src/core/generation-thread-registry.ts',
        'src/core/model-catalog.ts',
        'src/core/runtime/capability-manifest.ts',
        'src/core/runtime/runtime-event-reducer.ts',
        'src/core/runtime/runtime-json-value.ts',
        'src/core/runtime/runtime-negotiation.ts',
        'src/core/runtime/runtime-protocol.schemas.ts',
        'src/core/runtime/runtime-run-budget.ts',
        'src/core/runtime/runtime-tool-contracts.ts',
        'src/core/runtime/runtime-tool-normalization.ts',
        'src/core/permission-policy.ts',
        'src/core/redaction.ts',
        'src/core/run-boundary.ts',
        'src/core/session-lock.ts',
        'src/core/session-vault.ts',
        'src/core/sse-decoder.ts',
        'src/core/workspace-mutation-gate.ts',
        'src/core/workspace-path-policy.ts',
        'src/core/workspace-scope.ts',
        'src/services/chat-service.ts',
        'src/services/agent-context-service.ts',
        'src/services/agent-connection-service.ts',
        'src/services/agent-execution-presenter.ts',
        'src/services/agent-run-guards.ts',
        'src/services/agent-run-service.ts',
        'src/services/attachment-request-service.ts',
        'src/services/attachment-upload-service.ts',
        'src/services/conversation-session-service.ts',
        'src/services/generation-scheduler.ts',
        'src/services/model-service.ts',
        'src/services/prompt-execution-service.ts',
        'src/services/runtime-protocol-service.ts',
        'src/services/safe-edit-service.ts',
        'src/services/session-control-service.ts',
        'src/services/workflow-service.ts',
        'src/infrastructure/vscode-workspace-edit-adapter.ts',
        'src/infrastructure/vscode-runtime-target-adapter.ts',
      ],
      thresholds: {
        branches: 85,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
  },
});
