import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: ['tests/{unit,integration}/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: [
        'src/backend/backend-client.ts',
        'src/core/configuration.ts',
        'src/core/chat-attachment.ts',
        'src/core/context-collector.ts',
        'src/core/edit-plan.ts',
        'src/core/extension-state.ts',
        'src/core/model-catalog.ts',
        'src/core/permission-policy.ts',
        'src/core/redaction.ts',
        'src/core/run-boundary.ts',
        'src/core/session-lock.ts',
        'src/core/session-vault.ts',
        'src/core/sse-decoder.ts',
        'src/core/workspace-scope.ts',
        'src/core/workspace-path-policy.ts',
        'src/services/chat-service.ts',
        'src/services/agent-connection-service.ts',
        'src/services/agent-execution-presenter.ts',
        'src/services/agent-run-service.ts',
        'src/services/attachment-request-service.ts',
        'src/services/attachment-upload-service.ts',
        'src/services/conversation-session-service.ts',
        'src/services/generation-scheduler.ts',
        'src/services/model-service.ts',
        'src/services/prompt-execution-service.ts',
        'src/services/safe-edit-service.ts',
        'src/services/session-control-service.ts',
        'src/services/workflow-service.ts',
        'src/infrastructure/vscode-workspace-edit-adapter.ts',
      ],
      thresholds: {
        branches: 85,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
  },
});
