import type { RuntimeJsonObject } from './runtime-tool-contracts';

const text = { type: 'string', maxLength: 1_048_576 } as const;
const integer = { type: 'integer', minimum: 0, maximum: 16_777_216 } as const;
const flag = { type: 'boolean' } as const;
const opaque = { type: 'object', properties: {}, additionalProperties: true } as const;
const texts = { type: 'array', items: text, maxItems: 10_000 } as const;
const integers = { type: 'array', items: integer, maxItems: 1_000 } as const;
const objects = { type: 'array', items: opaque, maxItems: 1_000 } as const;

function strict(properties: RuntimeJsonObject): RuntimeJsonObject {
  return { type: 'object', properties, additionalProperties: false, maxProperties: 64 };
}

export const runtimeToolInputSchemas = {
  agents: strict({ graph: opaque }),
  browser: strict({
    sessionId: text,
    contextId: text,
    pageId: text,
    url: text,
    locator: opaque,
    targetLocator: opaque,
    value: text,
    values: texts,
    relativePaths: texts,
    artifactPath: text,
    viewport: opaque,
    timeoutMs: integer,
    fullPage: flag,
    attempts: integer,
    intervalMs: integer,
    requestTimeoutMs: integer,
    expectedStatuses: integers,
    processSessionId: text,
  }),
  command: strict({
    executable: text,
    arguments: texts,
    cwdRootKey: text,
    cwd: text,
    environment: opaque,
    timeoutMs: integer,
    outputLimitBytes: integer,
    expectedEffect: text,
    targetId: text,
    elevation: flag,
    stdin: text,
    shell: opaque,
  }),
  container: strict({
    rootKey: text,
    engine: text,
    resource: text,
    tail: integer,
    contextPath: text,
    dockerfile: text,
    tag: text,
    image: text,
    name: text,
    arguments: texts,
    ports: objects,
    environment: opaque,
    receipt: opaque,
    executable: text,
    stdin: text,
    composeFile: text,
    projectName: text,
    services: texts,
    service: text,
  }),
  database: strict({
    rootKey: text,
    profileId: text,
    statement: text,
    rowLimit: integer,
    timeoutMs: integer,
    outputLimitBytes: integer,
    backupAcknowledged: flag,
  }),
  evidence: strict({ input: opaque, bundle: opaque, output: opaque }),
  files: strict({
    rootKey: text,
    path: text,
    startLine: integer,
    endLine: integer,
    maxBytes: integer,
    cursor: integer,
    limit: integer,
    pattern: text,
    maxResults: integer,
    query: text,
    transaction: opaque,
  }),
  git: strict({
    rootKey: text,
    path: text,
    ref: text,
    branch: text,
    startPoint: text,
    paths: texts,
    message: text,
    amend: flag,
    includeUntracked: flag,
    remote: text,
    refspec: text,
    forceWithLease: opaque,
    name: text,
    target: text,
  }),
  integration: strict({ request: opaque }),
  intelligence: strict({ identity: opaque, query: text, nodeIds: texts, paths: texts }),
  journal: strict({ journal: opaque, query: text, runId: text }),
  planning: strict({ plan: opaque, output: opaque }),
  process: strict({
    executablePath: text,
    arguments: texts,
    cwdRootKey: text,
    cwd: text,
    environment: opaque,
    columns: integer,
    rows: integer,
    title: text,
    readinessPattern: text,
    expectedPorts: integers,
    receipt: opaque,
    receipts: objects,
    data: text,
  }),
  quality: strict({ rootKey: text, scope: text, projects: objects, gateId: text }),
  services: strict({
    rootKey: text,
    definitions: objects,
    serviceIds: texts,
    serviceId: text,
  }),
} as const satisfies Readonly<Record<string, RuntimeJsonObject>>;
