import { EFFECT_KINDS, RISK_CLASSES, type ProjectPolicy } from '../../src/core/policy-v2';
import { classify } from '../../src/services/runtime-policy-v2-adapter';

import { decide, MATRIX_CEILINGS, MATRIX_MODES, type Verdict } from './permission-matrix';

import type { DiscoveredOperation } from './permission-matrix-discovery';

const LETTER: Readonly<Record<Verdict, string>> = { allow: 'A', ask: 'Q', deny: 'D' };
const MODE_LABEL = ['Plan', 'Strict', 'Ask', 'Auto', 'Full'] as const;
const CEILING_LABEL = ['none', 'Plan', 'Ask'] as const;

export interface MatrixRow {
  readonly key: string;
  readonly risk: string;
  readonly effect: string;
  /** Verdicts ordered ceiling-major, mode-minor, as in `MATRIX_CEILINGS` x `MATRIX_MODES`. */
  readonly verdicts: readonly Verdict[];
}

export async function buildMatrixRows(
  operations: readonly DiscoveredOperation[],
): Promise<readonly MatrixRow[]> {
  const rows: MatrixRow[] = [];
  for (const { tool, operation } of operations) {
    const classification = classify({ toolName: tool, operation } as Parameters<
      typeof classify
    >[0]);
    const verdicts: Verdict[] = [];
    for (const ceiling of MATRIX_CEILINGS) {
      for (const mode of MATRIX_MODES) {
        verdicts.push((await decide(tool, operation, { mode, ceiling })).verdict);
      }
    }
    rows.push({ key: `${tool}.${operation}`, ...classification, verdicts });
  }
  return rows;
}

async function projectRuleSection(operations: readonly DiscoveredOperation[]): Promise<string[]> {
  const lines = ['| Project policy | allow | ask | deny |', '| --- | ---: | ---: | ---: |'];
  const scenarios: readonly (readonly [string, Partial<ProjectPolicy>])[] = [
    ['none', {}],
    ...EFFECT_KINDS.map((effect): readonly [string, Partial<ProjectPolicy>] => [
      `deniedEffects: [${effect}]`,
      { deniedEffects: [effect] },
    ]),
    ...EFFECT_KINDS.map((effect): readonly [string, Partial<ProjectPolicy>] => [
      `requireApproval: [${effect}]`,
      { requireApproval: [effect] },
    ]),
    ...RISK_CLASSES.slice(0, 4).map((risk): readonly [string, Partial<ProjectPolicy>] => [
      `maximumRisk: ${risk}`,
      { maximumRisk: risk },
    ]),
  ];
  for (const [label, project] of scenarios) {
    const counts: Record<Verdict, number> = { allow: 0, ask: 0, deny: 0 };
    for (const { tool, operation } of operations) {
      const result = await decide(tool, operation, { mode: 'AUTONOMOUS_SCOPED', project });
      counts[result.verdict] += 1;
    }
    lines.push(
      `| \`${label}\` | ${String(counts.allow)} | ${String(counts.ask)} | ${String(counts.deny)} |`,
    );
  }
  return lines;
}

function header(): string[] {
  const columns = CEILING_LABEL.flatMap((ceiling) =>
    MODE_LABEL.map((mode) => `${mode}${ceiling === 'none' ? '' : ` / ${ceiling}`}`),
  );
  return [
    `| Operation | Risk | Effect | ${columns.join(' | ')} |`,
    `| --- | --- | --- | ${columns.map(() => ':-:').join(' | ')} |`,
  ];
}

export async function renderPermissionMatrix(
  operations: readonly DiscoveredOperation[],
): Promise<string> {
  const rows = await buildMatrixRows(operations);
  const body = rows.map(
    (row) =>
      `| \`${row.key}\` | ${row.risk} | ${row.effect} | ${row.verdicts.map((v) => LETTER[v]).join(' | ')} |`,
  );
  const table = header();
  return [
    '# Permission matrix',
    '',
    '<!-- Generated by `npm run permissions:matrix`. Do not edit by hand: a test fails when this file is stale. -->',
    '',
    `Every tool operation the runtime registers (${String(rows.length)}), the risk class and effect the policy assigns it, and the decision the real \`RuntimePolicyV2Adapter\` reaches for it. Decisions are computed by running the adapter, not restated here. See [ADR 0003](adr/0003-permission-modes-under-an-organization-ceiling.md).`,
    '',
    '**Decision:** `A` allow without asking, `Q` ask the user first, `D` deny.',
    '',
    "**Columns:** the mode, then `/ Plan` or `/ Ask` when an organization ceiling of that name applies (no suffix means no ceiling). **Modes:** Plan, Strict (`ENTERPRISE_LOCKED`), Ask, Auto (`AUTO_EDIT`), Full (`AUTONOMOUS_SCOPED`). **Ceiling:** the organization's `minimumPermissionMode`; a mode above it is clamped down to it. Trusted workspace, user present, no project rules.",
    '',
    '## Untrusted workspace',
    '',
    'Every operation below is `D` (`WORKSPACE_UNTRUSTED`) in every mode and under every ceiling. Untrusted workspaces also start no lifecycle hook, no stdio MCP server, no scheduled task and no plugin-supplied local server; `tests/unit/permission-matrix.test.ts` asserts each.',
    '',
    '## Per-operation decisions',
    '',
    ...table,
    ...body,
    '',
    '## Project policy',
    '',
    `How a project's \`.clawai/policies/policy.json\` narrows the same ${String(rows.length)} operations in Full mode, trusted workspace. A project can only tighten; deny beats every ask and allow.`,
    '',
    ...(await projectRuleSection(operations)),
    '',
  ].join('\n');
}
